services:
  loki:
    image: grafana/loki:3.0.0
    container_name: tp-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: tp-alloy
    ports:
      - "12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./apps_logs:/var/log/apps:rw
    command: run --storage.path=/var/lib/alloy/data --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    user: root
    depends_on:
      - loki
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: tp-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - observability

networks:
  observability:
    driver: bridge